Feature/new patient form
UTN-FRBA-Mobile/Disfluency pull request #6
Opened 2023-06-01 01:29 UTC by matiasanz

- Page to create new patients, with fields. It's scrollable.
     - "name" and "lastname" (both starting with Caps), "dni" (only numbers), "email" (validated by regex), "joinedSince" (date it was created) & dateOfBirth (written thru a DatePicker with calendar option and it must be before date of join).
 - All of theese parameters are required and validated, showing message on error.
 - Unused input for patient image.

2023-06-02 16:19 UTC, AgustinCragno commented on app/src/main/java/com/disfluency/screens/pacientes/Patient.kt
Esto habria que dejarlo con el formato de carpetas que esta en main, seria main/java/com/disfluency/model/Patient. De todas formas antes de mergear vas a tener que traerte lo que esta en main y unir todo, pero eso si quieren nos juntamos y lo hacemos

2023-06-02 16:21 UTC, AgustinCragno commented on app/src/main/java/com/disfluency/screens/pacientes/PacientesScreen.kt
> +        if(displayedNewPatient){
Esto esta mal me parece. No se que opinan @JulianSima @josebruzzoni, pero entiendo que esto deberia hacerse con otra pantalla, otra ruta. Y que al tocar en el boton de nuevo paciente te redireccione a la pantalla de FormNewPatient, y que al tocar cancelar en formnewpatient te redireccione a pacientes

2023-06-02 16:22 UTC, AgustinCragno commented on app/src/main/java/com/disfluency/screens/pacientes/formNewPatient.kt
> +    Button(
aca aprovechemos los modifiers de los composables, se le puede agregar un padding al boton para que no quede pegado a la nav bar abajo y quede con una separacion

2023-06-02 16:23 UTC, AgustinCragno commented on app/src/main/java/com/disfluency/screens/pacientes/formNewPatient.kt
Es una re pavada jaja, pero por convencion van los nombres de los archivos en mayuscula. Para los composables tambien. Creo que las funciones nomas van en minuscula

2023-06-02 16:27 UTC, AgustinCragno commented on app/src/main/java/com/disfluency/screens/pacientes/inputs.kt
> +        , label = { Text(label) }
otra boludes jajaj pero aca y un cacho arriba quedaron las comas al principio de la oracion

2023-06-02 16:30 UTC, AgustinCragno commented on app/src/main/java/com/disfluency/screens/pacientes/inputs.kt
> +    var value by remember { mutableStateOf("") }
Aca estuve mirando y entiendo que esto no se debe usar asi, la idea es que el estado se cree mas arriba y se lo pase por parametro al input para que se llene, los composables entiendo no deben devolver estados sino modificarlos. 

Aca estuve leyendo dos posts con ejemplos de input
https://medium.com/@manojbhadane/android-login-screen-using-jetpack-compose-part-1-57ecfc74e428
Este un cacho mas complejo pero explica banda tambien
https://medium.com/androiddevelopers/effective-state-management-for-textfield-in-compose-d6e5b070fbe5

2023-06-02 16:32 UTC, AgustinCragno requested changes
Ahi deje un par de comentarios, si quieren en estos dias nos juntamos unos minutos y los revisamos

2023-06-02 17:11 UTC, matiasanz commented on app/src/main/java/com/disfluency/screens/pacientes/Patient.kt
Me parece mejor verlo entre varios. Estuve por acomodarlo, pero como esta el paciente duplicado y seguro haya que adaptar alguna que otra cosa, preferi dejarlo en un mismo lugar asi queda a mano por las dudas.

2023-06-02 17:22 UTC, matiasanz commented on app/src/main/java/com/disfluency/screens/pacientes/PacientesScreen.kt
> +        if(displayedNewPatient){
Si, la idea sería esa, pero como lo de redireccionar se agrego despues, me quedo de esta forma. El column pasaría a FormNewPatient y el parámetro "onsubmit" era solo para acceder a la lista de pacientes, que habra que reemplazar por el repo

2023-07-02 19:58 UTC, AgustinCragno approved these changes

2023-07-02 19:58 UTC, merged